"""Bundled EMV offline authentication sample vectors for GREENWIRE tests.

These vectors were generated by `tools/generate_emv_sample_vectors.py` and are
used to exercise the SDA, DDA, and CDA verification routines without requiring
live card data.  All values are hexadecimal representations that are converted
into bytes on demand.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict

from binascii import unhexlify


@dataclass(frozen=True)
class OfflineAuthSample:
    """Static sample data set for EMV offline authentication flows."""

    rid: str
    ca_key_index: str
    ca_modulus_hex: str
    ca_exponent_hex: str
    issuer_pk_cert: bytes
    issuer_pk_remainder: bytes
    issuer_pk_exponent: bytes
    icc_pk_cert: bytes
    icc_pk_remainder: bytes
    icc_pk_exponent: bytes
    signed_static_data: bytes
    static_payload: bytes
    signed_dynamic_data: bytes
    dynamic_payload: bytes
    signed_cda_data: bytes
    cda_payload: bytes

    def ca_key_record(self) -> Dict[str, str]:
        """Return a dictionary compatible with `ca_keys.json`."""

        return {
            "rid": self.rid,
            "index": self.ca_key_index,
            "modulus": self.ca_modulus_hex,
            "exponent": self.ca_exponent_hex,
        }


_SAMPLE_VECTORS_HEX = {
    "rid": "A0000000F0",
    "ca_key_index": "01",
    "ca_modulus_hex": "AF02AE5D26C5B7B269737D74D84FB920BF29D733CC726B96FAFAA917202ACB1005471E2CD1946E7CCEEAC24D3C48FCEEAB563388E6B2A11842784E4CC0D8BABC20AAE60314BAECC827756C69988EED81542FFB622B308D5371B54B18CADB0ACF",
    "ca_exponent_hex": "10001",
    "issuer_public_key_certificate": "262F3CDBB7EF2F14318E5F1CAED4E6901D88EF2ACACC3D2C1F54658D8723A85E2BC7634C3912D7716E28E80080E334B7A897BDAA304DBFB6CDEF80C9CA1E469E80DA8BDED718D2A69618121F3BADB4A36B63581CFDE1246A42EF77933A01FDC8",
    "issuer_public_key_remainder": "850E698F5796C06256745BEE310ACADAB03B3C409E433EC1EFAC57FD",
    "issuer_public_key_exponent": "010001",
    "icc_public_key_certificate": "369E3A0CC46EA7145B52E7BA1544A67E0D3A822DE678CE60DA1AB0CA96E1679F4BDD725FF46C7D7A45630F261423D59F8F8731621B47E66C74B1274CD65457BC20C50552E28DF8FF2F0922DC5EBE48CCC589EBC4665BF5B3",
    "icc_public_key_remainder": "83CEE6ED1863D0FA2A0970C9096FB1DDCD92370BDA6D7AEDA02D3647CC525B0ECE2D",
    "icc_public_key_exponent": "010001",
    "signed_static_data": "18293A5330EF4A2162A0FE22180311A49D470393ED6A58CF19E54BAFF72F28208C88930603EC0E0033210DB51AC29BDE406BACFA8B002342109CF3B629F8226D532D60093646B7206444FBAFA111399ABE2C51DBA69104CB",
    "static_payload": "701EAABBCCDDEEFF00112233445566778899AABBCCDDEEFF0102",
    "signed_dynamic_data": "7416631438C8236074EC936D2B3B39DFD057615591D6F8234C7532760299A22DEF393BA69F0C4E92F8644C13447F7A7ECC12F80CE62FAB11B0305E6ED54CF55644C5AA5C577EF66C17CB2BC8F4E16A02",
    "dynamic_payload": "9F3704A1B2C3D49F36020001",
    "signed_cda_data": "7CC51232C958453C7E176F03EF2FCF52C10FDC7D08C127F44232E092661BE3EBBFCC62C2AEF10B5056A8193FCA093F1560699D1AB93A5FD2B47DE8FEA84591554DF756CF008E2B1DC7A14F7C958638DF",
    "cda_payload": "9F3704A1B2C3D49F360200019F2701A0",
}


def get_sample_vectors() -> OfflineAuthSample:
    """Return the offline authentication sample vectors as bytes."""

    return OfflineAuthSample(
        rid=_SAMPLE_VECTORS_HEX["rid"],
        ca_key_index=_SAMPLE_VECTORS_HEX["ca_key_index"],
        ca_modulus_hex=_SAMPLE_VECTORS_HEX["ca_modulus_hex"],
        ca_exponent_hex=_SAMPLE_VECTORS_HEX["ca_exponent_hex"],
        issuer_pk_cert=unhexlify(_SAMPLE_VECTORS_HEX["issuer_public_key_certificate"]),
        issuer_pk_remainder=unhexlify(_SAMPLE_VECTORS_HEX["issuer_public_key_remainder"]),
        issuer_pk_exponent=unhexlify(_SAMPLE_VECTORS_HEX["issuer_public_key_exponent"]),
        icc_pk_cert=unhexlify(_SAMPLE_VECTORS_HEX["icc_public_key_certificate"]),
        icc_pk_remainder=unhexlify(_SAMPLE_VECTORS_HEX["icc_public_key_remainder"]),
        icc_pk_exponent=unhexlify(_SAMPLE_VECTORS_HEX["icc_public_key_exponent"]),
        signed_static_data=unhexlify(_SAMPLE_VECTORS_HEX["signed_static_data"]),
        static_payload=unhexlify(_SAMPLE_VECTORS_HEX["static_payload"]),
        signed_dynamic_data=unhexlify(_SAMPLE_VECTORS_HEX["signed_dynamic_data"]),
        dynamic_payload=unhexlify(_SAMPLE_VECTORS_HEX["dynamic_payload"]),
        signed_cda_data=unhexlify(_SAMPLE_VECTORS_HEX["signed_cda_data"]),
        cda_payload=unhexlify(_SAMPLE_VECTORS_HEX["cda_payload"]),
    )


__all__ = ["OfflineAuthSample", "get_sample_vectors"]
