# GitHub Actions Workflow for GREENWIRE CI/CD
# This workflow automates the build, test, and deployment processes for the
# GREENWIRE project.
#
# Dependencies:
# - Python 3.11 with pip to install packages from ``requirements.txt``.
# - Java 17 and Gradle to build ``JCOPCardManager`` into ``GREENWIRE.jar``.
# - PC/SC compatible reader drivers (``pcscd``/``libpcsclite``) for smartcard
#   integration.
# The workflow is triggered on pushes and pull requests to the ``main`` branch.

name: GREENWIRE CI/CD

on:
  # Trigger the workflow on push and pull request events targeting the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Test job to run Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Check out the repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt flake8
      - name: Run Python tests
        # Run Python tests using pytest
        run: pytest --maxfail=5 --disable-warnings
      - name: Lint
        run: flake8

  deploy:
    # Deployment job placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying GREENWIRE project"
