# GitHub Actions Workflow for GREENWIRE CI/CD
# This workflow automates the build, test, and deployment processes for the
# GREENWIRE project.
#
# Dependencies:
# - Python 3.11 with pip to install packages from ``requirements.txt``.
# - Java 17 and Gradle to build ``JCOPCardManager`` into ``GREENWIRE.jar``.
# - PC/SC compatible reader drivers (``pcscd``/``libpcsclite``) for smartcard
#   integration.
# The workflow is triggered on pushes and pull requests to the ``main`` branch.

name: GREENWIRE CI/CD

on:
  # Trigger the workflow on push and pull request events targeting the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Build job to compile the Java project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Check out the repository code
        uses: actions/checkout@v4
      - name: Set up Java
        # Set up Java 17 environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Java class
        # Compile the JCOPCardManager class and package it into a jar
        run: |
          javac JCOPCardManager.java
          jar --create --file GREENWIRE.jar JCOPCardManager.class

  test:
    # Test job to run both Python and Java tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Check out the repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python tests
        # Run Python tests using pytest
        run: pytest -q
      - name: Compile Java
        run: javac JCOPCardManager.java

  deploy:
    # Deployment job to deploy the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Check out the repository code
        uses: actions/checkout@v4
      - name: Deploy
        # Placeholder for deployment script
        run: echo "Deploying GREENWIRE project"
